version: '2'
services:
  db:
    image: mongo
    volumes: 
      - ~/data:/data/db
    ports:
      - 27017:27017
  web:
    build: .
    depends_on:
      - db
    links:
      - db
    ports:
      - 8888:8888

